# Generated by Django 4.1 on 2024-01-10 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("inicio", models.DateTimeField(blank=True, default=None, null=True)),
                ("repetir", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Accion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                (
                    "accion_model",
                    models.CharField(
                        choices=[
                            ("screen", "screen"),
                            ("move", "move"),
                            ("write_text", "write_text"),
                            ("push_enter", "push_enter"),
                            ("wait", "wait"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("imagen", models.ImageField(blank=True, upload_to="screens/")),
                ("texto", models.CharField(max_length=200, unique=True)),
                ("orden", models.IntegerField()),
                (
                    "tareaID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acciones.tarea"
                    ),
                ),
            ],
        ),
    ]
