# Generated by Django 4.1 on 2024-01-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accion",
            name="texto",
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
