# Generated by Django 4.1 on 2024-01-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acciones", "0002_alter_accion_texto"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="habilitar",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accion",
            name="texto",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
