# Generated by Django 4.1 on 2024-01-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acciones", "0003_tarea_habilitar_alter_accion_texto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarea",
            name="habilitar",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
